npm install --save body-parser
npm install --save consign
npm install --save ejs
npm install --save express
npm install --save mysql2
npm install --save jquery
npm install --save popper.js
npm install --save bootstrap
npm install --save sequelize
npm install --save sequelize-cli
