INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'AGATHA AGUIAR FERREIRA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'AYLA LUIZA SOUZA ALVES', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'DAVI LUCAS ALVES ZONETTI', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'EDUARDO BRITO TAVARES', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'ELISA MAITHE FARIAS LOPES', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', '* Transf* ENZO MONTEIRO RODRIGUES', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', '*Transf* ESTHER FERNANDA DA SILVA ROCHA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', '*Transf* GIOVANNA OLIVEIRA ALMEIDA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'GUILHERME DA SILVA CARVALHO SOUSA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'HAGATA SANTIAGO STURCHI', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'IAN MIGUEL DE ASSIS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'ISABELLY DE ABREU DE LUCENA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'ISABELLY FRANÇA DE SANTANA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'ISACK GOMES LOURENÇO', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'IVO RODRIGUES', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'KETHELLIN VITORIA OLIVEIRA DE JESUS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'LAURA EMILLY ESTEVAO FERREIRA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', '*Transf* LORENA PEREIRA FIUSA DOS SANTOS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MANOELA DOS SANTOS SILVA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MARIA EDUARDA ROSA DA SILVA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MATHEUS SILVA DOS SANTOS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MIGUEL SILVA PEREIRA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'NICOLLY VENANCIO DA SILVA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', '*Transf* NICOLLY VITORIA CARVALHO DOS SANTOS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', '*Transf* PIETRO HENRIQUE DOS SANTOS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'RODRIGO FERNANDES SILVA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'SOPHIA DA SILVA PAIVA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'SOPHIA GOMES DE FRANCA', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'THAYLLA MYRELA BARRETO DOS SANTOS', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', '*Transf* WENZO GABRIEL SILVA FRAZAO', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'DANILO DA ROCHA BRITO', '1A Ezilda', '1');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', '*Transf* ANA BEATRIZ SILVA LOPES SENA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA CLARA CONCEICAO DE JESUS', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ARTHUR GABRIEL DOS SANTOS', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'BERNARDO CAPUCHO FREITAS PEREIRA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'BERNARDO OLIVEIRA MENDES', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'CALEBE GUERRA DA SILVA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'DAVI FREITAS DE SOUZA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'EMERSON DE ARAUJO PINHEIRO JUNIOR', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'ENZO FARIAS MENEZES SILVA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'ISABELLY DOS SANTOS', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'JEFERSON LUCAS LIMA CONCEICAO', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'JHENNIFER SOPHIA ARAUJO DE OLIVEIRA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', '*Transf* LETICIA PINHEIRO DIAMANTINO', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'LUCAS MIGUEL SILVA SANTOS', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'LUCAS SOUSA BERGMANN', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', '*Transf* LUIZA ROCHA DE OLIVEIRA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'MARIA VITORIA DA SILVA BARBOSA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'MIGUEL DE FRANCA PEREIRA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MIGUEL SANTOS DE QUEIROZ', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'NATHALLY LETICIA BARBOSA AMORIM', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'RAISSA SANTOS DE OLIVEIRA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', '*Transf* RAPHAEL DOS ANJOS TORRES', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'SAMUEL SANTANA ALVES', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'SOPHIA MAYUMI UCHIDA GARCIA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'STHEFANY NASCIMENTO FELIX CAVALCANTI', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'VICTOR TAVARES DA SILVA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', '*Transf* YASMIN ISIS NOVAES DE SOUZA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', '*Transf* YASMIN SILVA LOPES SENA', '1B Ezilda', '2');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ALICIA CAMISA LOPES', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA CLARA DA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANA CLARA FERNANDES DA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'ARTHUR JUNIOR DA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'BERNARDO EVANGELISTA DUARTE', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'DAVI FERNANDES DOS SANTOS', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'ENZO GABRIEL DE JESUS', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'EZEQUIEL XAVIER RIBEIRO', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'GABRIEL COELHO VIEIRA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'HIGOR PEREIRA DOS SANTOS', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'IAN TAQUETTO GARCIA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'ISABELLY FERNANDES FELIX', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', '*Transf* ISADORA FELIZARDO BERNAL', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'ISAQUE SEVERINO MARQUES DA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'JHONY MIGUEL VIVAQUA DELFINO', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JOZIELSON PEREIRA DA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'KYARA VITORIA MARCIANO DE SOUZA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LINCOLN ALVES', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MATHEUS FERNANDES', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MIGUEL JANUARIO SANTOS SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MIGUEL SILVA DE FREITAS', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'PAMELA VERAS SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', '*Transf* RAFAEL DOS SANTOS GOMES', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'RHAMON VINICIUS GOIS DE CARVALHO', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'RONALD BATISTA DE JESUS', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', '*Transf* RUNEY NERI JUCA SILVA', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', '*Transf* THEO BITTENCOURT CARTACHO', '1C Ezilda', '3');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', '*Transf* AGATHA MARQUES DOS SANTOS', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', '*Transf* ANA HELLEN FELIX DE SOUSA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ARTHUR BARTOLOMEU ROCHA SANTOS', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'BRYAN RENAN DE OLIVEIRA DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'CELINA MARIAH CAROBA DIAS', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'ELOA BEZERRA DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'EMANUELLY BORGES DE ANDRADE', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'ENZO SOUZA CRUZ', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'FELIPE GABRIEL LISBOA DE LIMA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'FRANCIELLY DOS SANTOS COSTA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'GABRIEL LOURENCO DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', '*Transf* GUILHERME HENRIQUE LIMA MUNIZ DIAS', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'HELLENA RIBEIRO SOARES', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'ISABELLY RODRIGUES DA SILVA BULHOES', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', '*Transf* JOAO MIGUEL DOS SANTOS AMORIM', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JULIA CARDOSO ALVES MIRA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'JULIA PEREIRA DA COSTA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LAURA KAROLAINE CABRAL RODRIGUES', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'LIVIA ROBERTO DIAS DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MARIA LUIZA CARVALHO SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MARIANA DINIZ DE LIMA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MAURICIO DAVI DE JESUS SANTANA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MIGUEL CARVALHO DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', '*Transf* MIGUEL GOMES DOS SANTOS', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', '*Transf* PAULO CESAR DE SOUSA FERREIRA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', '*Transf* PEDRO HENRIQUE GOMES BUENO', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', '*Transf* PIETRO CORDEIRO DA SILVA', '1D Ezilda', '4');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ALICE JORGE LUCIO', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA HELOISA DE SOUSA FERNANDES ALVES', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANDRE LUCAS DA SILVA VIVAQUA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'A*Transf* RTHUR ARAGAO DE LIMA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'ARTHUR OLIVEIRA DE CARVALHO', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', '*Transf* BRAYAN MACEDO SILVA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', '*Transf* DAVI LUIS DA SILVA SALES', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', '*Transf* ENZO GOMES DANTAS', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'FERNANDA DE SOUZA BARBOSA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'GEOVANA ARAUJO BRITO', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', '*Transf* HEITOR LEONIDIO DIAS', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'HELOISA SILVA DE MOURA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'HENRIQUE MIGUEL VASCONCELOS XAVIER', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'ISABELLA MATOS DA SILVA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'JOAO MARCO DE ALCANTARA ROCHA SANTOS', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JONATAS DE SANTANA COCA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'LAURA PAULINO DE JESUS', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', '*Transf* LUIZ HENRIQUE MARTINS PLAZA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MIGUEL DUARTE GOMES VITAL', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', '*Transf* MIKAELLA ALVES NUNES', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'PEDRO SILVA GARCIA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', '*Transf* PYETRO DA SILVA DUARTE CABRAL', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'RAFAEL CUSTODIO MARQUES', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', '*Transf* REBECA LARISSA DA SILVA BARRETO', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'RICHARD CORREA DE ASSIS', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'RYANNA CECILIO BARBOSA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'SAMUEL CAVALCANTE DE SANTANA LIRA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'WAGNER PIETRO REGIS DA SILVA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'YAGO BRAYAN DUARTE DA SILVA', '1E Ezilda', '5');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ANA CAROLINA AMARAL DO NASCIMENTO', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'BRYAN RAFAEL MARIANO', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'DAVI BARBOSA VIEIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'DAVI LUIZ FARIAS MESQUITA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'ENZO RODRIGUES DIAS', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', '*Transf* FELIPE FEITOSA DONEDA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'FELIPE GABRIEL DA SILVA LIMA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'GABRIELLE DA SILVEIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'HELOA NARDES RIBEIRO', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'JENNIFER VITORIA DE SOUSA LOMBARDI', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'JULIA ROSEANE PAVIM PEREIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'KEMILLY RAQUEL DE SANTANA PEREIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'LETICIA OLIVEIRA SANTOS DA SILVA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'LIVIA DA SILVEIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'LORENA DE SOUZA MEIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'MARIA RITHA DE SOUZA ALMEIDA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'MATEUS REIS ALVES', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', '*Transf* MIGUEL ANDRADE SOUSA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MURILO SOUSA SANTOS', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'NATHAN RICHARD SANTIAGO ARAUJO', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'NICOLLY LEITE PEREIRA DA SILVA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'PEDRO HENRIQUE FARIAS ANDRADE', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'RAFAELA MOTA SILVA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'RAISSA VITORIA FELIX DA SILVA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'SAMUEL INACIO MARINHO TEIXEIRA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'SARA BARROS LIMA', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'SOPHIA FERREIRA ALVES DE ALENCAR', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'YASMIN VITORIA TROVALIM PIRES', '1F Ezilda', '6');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ALLAN SANTOS SILVA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'BRUNO COSTA DE SOUSA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'CIARA AVELINO DA SILVA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'DAVI DE FREITAS SILVA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'DAVY EVANGELISTA JESUS DE SOUZA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'DIOGO HENRIQUE SILVA MIKAIL', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'EMILLY DO CARMO AFFONSO', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'ENZO DE OLIVEIRA FERREIRA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'GABRIELLA NASCIMENTO SOUSA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'GABRIELLY SANTOS DINIZ', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'HERMIONE VALENTINA LAZARINI MARTINS NOGUEIRA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'ISABELLY LOHAYNE DA SILVA AGUIAR', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'JENNIFER EDUARDA DA SILVA SANCHES', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'KAUAN DOS SANTOS RODRIGUES', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'LORRAYNE MELISSA DE OLIVEIRA SANTOS', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'LUISA NASCIMENTO DE SOUZA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'MARIA HELOISA FERREIRA RODRIGUES', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'MIGUEL DE SOUZA ALMEIDA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MIGUEL NEVES DE ANDRADE CESAR', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MIGUEL ROCHA DA SILVA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MURILLO DAVI DE SOUSA SANTOS', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'RYAN GABRIEL SANTOS TELES', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'SAMUEL CABRAL DA SILVA', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'SOPHIA MARES CARDOSO', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'VITTOR OSCAR SOUZA CRUZ', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'LUIZA BERNARDO ZAPELLI', '2G Ezilda', '7');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ADRIEL DE LIMA SILVA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA LIVIA MARTINES DE SOUZA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ARTHUR SANTOS PALMEIRA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'ARTUR EVANGELISTA CAMPOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'BEATRIZ BEZERRA CAETANO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'BRENDA APARECIDA COSTA DE SOUSA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'BRUNO DANIEL COSME DANTAS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'CAIQUE TAVARES BATISTA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'DEIVYSON GABRIEL DA SILVA LAURENTINO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'EVELLYN SANTOS BARREIROS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'FELIPE GABRIEL CRUZ SILVA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'GABRIELLY RAMALHO LUNA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'GIOVANNA QUADROS DOS SANTOS FONSECA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'HANNA MAYSA LOPES ALVES DOS SANTOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'HENRY DA SILVA MEDEIROS SANTOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JOAO VICTOR DE OLIVEIRA SANTOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'LEVI SACRAMENTO ALVES', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LORENA VITORIA PEREIRA DA SILVA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'LUAN DA SILVA COUTINHO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'LUCAS SANTANA SANTOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MACKSON LUCAS SILVA DO NASCIMENTO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MIGUEL LOURENCO DE ALMEIDA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MILENI COSTA SANTOS', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'RYAN RONCOLATO DA SILVA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'SAMIRA DE LIMA NOGUEIRA', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'SONIA FERNANDA PINTO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'VINICIUS DANIEL DA SILVA CAVALHEIRO', '2H Ezilda', '8');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ANA PAULA SOUZA SANTOS', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ARTHUR ALVES DA SILVA MELO', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'BRENDA DE SOUZA GAMACCI', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'BRUNO GARCIA DONZEL DA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'DIOGO GOMES DA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'EDUARDO HENRY PEREIRA DA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'EDUARDO PEDREIRA GONCALVES', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'ENZO DOMINGUES FERREIRA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'GABRIEL DE CARVALHO SILVA RODRIGUES', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', '*Transf* GABRIEL DO CARMO DE SANTANA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'GABRIEL MOTA DA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'GRAZIELLY SILVA SOUZA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'ISAAC DE SOUSA FERNANDES ALVES', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'JULIA VIANA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'KALEB MATOS SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', '*Transf* KAUANNY DE MELO FEITOSA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'KEVIN VIEIRA DE OLIVEIRA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LAURA MARTINS CAVALCANTE', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MARIA GABRIELY MIRANDA ARAUJO', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MIGUEL YURY MARCIANO DE SOUZA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MILENA GOES DO NASCIMENTO', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'NATAN DE SOUZA MEIRA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'NICOLAS DE LIMA MATOS', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'THAYLON SANTANA XAVIER', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', '*Transf* TIAGO ALVES LIMA LANDIM', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'WILLIAM EMERSON DA SILVA', '2I Ezilda', '9');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ANA CLARA PEREIRA VIANA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA FLAVIA MARTINS DA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANTHONY PRUDENCIO COELHO', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'CAMILLY VITORIA XAVIER MARQUES', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'CARLOS EDWARD BATISTA DA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'DIEGO IZIDORO GONCALVES', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'ENZO RODRIGUES DOS ANJOS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'GABRIELLY LOURENCO DA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'ÍTALO GABRIEL CAVALCANTE SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'JOAO VITOR GOMES CANTANHEDE DOS SANTOS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'KAIO GABRYEL SILVA ROCHA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'KAMILLY BEATRIZ BELO DE CARVALHO', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'KAUA NUNES DA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'KIMBERLY DA FE SOUSA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'LUCAS PEDREIRA SANTANA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'MARCOS PAULO DOS SANTOS SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'MARIA EDUARDA DE OLIVEIRA ROCHA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'MARIA EDUARDA DINIZ DE LIMA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'MATEUS DE SOUZA BARROS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MATHEUS SILVA SANTOS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MATHEUS VINICIUS OLIVEIRA DE ARAUJO', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MIGUEL JUNIOR ALMEIDA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MILENY PRADO DE OLIVEIRA SILVA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'MURILO CAPUCHO FREITAS PEREIRA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'NICOLLE ALVES DO COUTO', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'PAULO DANIEL MARTINS BORGES', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'PEDRO HENRIQUE BRUGNARI GOMES', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'PEDRO HENRIQUE DE LIMA ALMEIDA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'REBECA DOS SANTOS FERREIRA DE MEDEIROS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', 'TAWANE EMANUELA FERREIRA DOS SANTOS', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'VICTORIA NAZARE ALBUQUERQUE DE SOUZA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32', 'YASMIN TARSITANO DA SILVA TAMBARA', '3A Ezilda', '10');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ANA CAROLINI ZORZETTO LUCIO', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANDRESSA DOS ANJOS OLIVEIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANDREY DOUGLAS RODRIGUES LEITE', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'ARTUR SANTANA ALVES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'ASAF GABRIEL FREITAS JANUARIO', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'BRAYAN ALVES PEREIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'BRYAN DE ARAUJO GOMES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'CINARA MAYANA SANTOS SILVA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'DAVI DA CONCEICAO DIAS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'EDDY EDUARDO SOUSA ARAUJO', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'ELIEL RODRIGUES NETO', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'EMILLY SOPHIA DOS SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'GABRIELLY VIEIRA SANTANA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'HENRIQUE XAVIER MENDES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'ISABELLE LIMA DOS SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'IZABELLY VITORIA NUNES DA SILVA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'JHONNY GABRIEL VASCONCELOS XAVIER', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LARYSSA LARA LISBOA FERREIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'LUCAS GABRIEL OLIVEIRA RODRIGUES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'MARIA CLARA DE CARVALHO', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MARIA JULIA XAVIER SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MATHEUS DA SILVA GELSOMINI', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MIGUEL CAIRES RODRIGUES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'MIRYAN EDUARDA BARRETO DOS SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'MURILO SANTOS INEZ', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'PAMELA MARIA ALVES DIAS DE OLIVEIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'PAULO SERGIO DE OLIVEIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'PEDRO HENRIQUE VIEIRA LOPES', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'RYAN DA COSTA DOS SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', 'RYAN SCHELEDER SILVA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'VICTOR MACEDO FERREIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32', 'VINICIUS FLORENCIO OLIVEIRA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33', 'YAN KELVYN DUARTE OLIVEIRA DOS SANTOS', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('34', 'YASMIN SILVA DE SOUSA', '3B Ezilda', '11');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ANA CLARA DA CONCEICAO RODRIGUES', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA JULIA DA SILVA MARQUES', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANDRE OLIVEIRA SILVA DOS SANTOS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'BRUNO BARBOSA DOS SANTOS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'CHRIS JUNIOR ALVES SILVA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'DANIEL DE OLIVEIRA ALVES', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'DANIENY YASMIM FRANCO DA SILVA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'DHENY SAMYLE RODRIGUES DE FREITAS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'EDUARDA OLIVEIRA SANTOS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'EMILLY DE SOUZA ALMEIDA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'FELIPE MIGUEL BEZERRA DA LUZ', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'ISABELLA CECILIA RODRIGUES DA SILVA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'JADE ELOA SCHELEDER FAUSTINO', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'JENIFFER RAWANE MARTINS CAVALCANTI', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'JHENYFER DA SILVA SANTOS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JOAO PEDRO DE OLIVEIRA SOUSA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'KARLOS ALBERTO FAGUNDES OLIVEIRA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'LAURA BANDEIRA MARCIAL DE MOURA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'LETICIA SANTANA CARDOSO', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'LIVIA VITORIA GOMES PAULINO', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'LORENA LOHAINE PERLIN ALVES', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'LUIZ MIGUEL PESSOA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MARCOS VINICIUS LIMA SILVA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'NICOLAS HENRIQUE MORAES CARDOSO', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'NICOLAS SOARES DE BARROS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'PEDRO HENRIQUE MOURA DE SOUZA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'RAFAELA EDUARDA LIMA MUNIZ DIAS', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'ROBERT JUNIOR PEGO FEITOZA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'RONALDO PRADO DE OLIVEIRA SILVA', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', 'SOPHIA CAROLINA CAVALCANTE NERES', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'SOPHIE AGUIAR DE ABREU', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32', 'VITOR HUGO ROCHA AVALLONE', '5A Ezilda', '12');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ALESSANDRA ARAUJO DOS SANTOS ASSIS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANTONIO SALES PEREIRA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ARTUR HENRIQUE OLIVEIRA CARLOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'AVILA ARAUJO DA SILVA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'BRUNA OLIVEIRA BAADER DA SILVA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'CAIO SILVA CAVALLIERI DOS SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'CAUA SANTANA MARTINS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'EDUARDO NUNES ALVES ZACARIAS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'ELLEN DA SILVA SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'ESTEFANI ANABEL DE ALMEIDA RAMOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'FRANCISCO JEFERSON PEREIRA SOUSA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'GISELLY DA SILVA GOMES', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'GRAZIELLY SILVA SOUSA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'HELLEN NASCIMENTO SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'HIGOR CECILIO DE ALMEIDA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'IGOR HENRIQUE DO NASCIMENTO SILVA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'ISABELLA ANDREZA ZACHARIAS SILVA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'JUAN BISPO CARDOSO', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'KAIQUE RITHELLE DOS SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'LARISSA HENRIQUE DE SOUZA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'LUCAS NUNES LUCAS DA SILVA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'LUIZ FABIANO APARECIDO DOS SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MARIA HELOISA MACIEIRA PEREIRA DOS SANTOS', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'MATHEUS SANTOS DO LAGO', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'MAYCON LIAN DA SILVA TEIXEIRA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'MIRELLA PAIVA DE ALMEIDA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'MURILO GUSTAVO LUNA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'NICOLE FERREIRA GOMES ALEXANDRINO', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'PAULO EDUARDO DOS SANTOS OLIVEIRA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', 'PEDRO ARTHUR DO VALE ROCHA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'RYAN HERNANDES ARAUJO SOARES', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32', 'THIFANY NICOLLY AMORIM LIMA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33', 'YASMIN VICTORIA DE SOUZA FERREIRA', '5B Ezilda', '13');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1', 'ADRIANO LIMA DE OLIVEIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2', 'ANA BEATRIZ DA CUNHA LIMA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3', 'ANA BEATRIZ SOUZA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4', 'ANGELINA SPINELI DE OLIVEIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5', 'CAMILA DO NASCIMENTO SANTOS', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6', 'DERYCK ALEXANDRE MOTA CORREIA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7', 'EMANUEL DA SILVA PROSPERO', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8', 'EVILLYN LOHANNY THEODORA GUERREIRO', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9', 'GABRIEL MARIANO DE ALMEIDA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10', 'GABRIEL VIEIRA FERREIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11', 'GABRIELLY FLORES LIMA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12', 'GUSTAVO HENRIQUE DA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13', 'HELLEN RIOS ESCOBAR', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14', 'ISABELA CRISTINA COUTINHO CARVALHO', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15', 'JULIA CRISOSTOMO DE ALCANTARA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16', 'JULIA LUSTOZA DE LIMA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17', 'KAIO SOUSA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18', 'KETHILYN ESTRELA SANTIAGO STURCHI', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19', 'LIVIA QUINTILHANO DA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20', 'LORRAINY ALMEIDA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21', 'MAYSA CARVALHO DE OLIVEIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22', 'MICAEL BEZERRA DOS SANTOS', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23', 'MIGUEL DOS SANTOS FERREIRA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24', 'MIGUEL MARTINS FERREIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25', 'MILENA ESTER FEITOZA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26', 'NAIARA BRITO OLIVEIRA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27', 'PABLO BONFIM SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28', 'PAULO FERREIRA TAVARES', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29', 'RIHANNA EDUARDA GOMES DOS SANTOS', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30', 'RYAN DA SILVA SANTOS', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31', 'SAMYRA CRISTINA DOS SANTOS', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32', 'TAYLINE JAINE DA SILVA', '5C Ezilda', '14');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33', 'WELLINGTON CARDOSO RAMOS', '5C Ezilda', '14');
