INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ALANYS SANTANA DOS SANTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANA JULIA RODRIGUES ALVES','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','BIANCA OLIVEIRA CAVALCANTI DE BRITO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','*Transf* BRUNO CESAR DOS SANTOS CARMO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','DAVID JUVINO SANTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','DAVY LUKAS DOS SANTOS BATISTA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','GEOVANNY DA SILVA RODRIGUES','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','HIGOR LUAN DA SILVA TEIXEIRA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','HUGO NUNES MONTEBELLO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','JOAO VITOR CARDOSO SILVA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','JULIO CESAR DA COSTA SILVA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','KAIQUE SILVA ARAUJO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','KAYO ARTTHUR SOUZA CECILIO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','LAVINIA SILVA MATTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','LUCAS DE SIBIA RIBEIRO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','LUCAS HENRIQUE DA SILVA PACO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','LUIS MIGUEL SANTOS DE JESUS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','LUIZ MIGUEL DE JESUS DO NASCIMENTO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','MARIA EDUARDA PEREIRA DE CARVALHO','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','MARIA EDUARDA RODRIGUES','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','MARIA EDUARDA VIEIRA DO VALE','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','MATHEUS SANTOS DOS REIS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','MURILO NUNES DE OLIVEIRA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','NADIA MARIA ALVES GOMES','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','*Transf* NAYARA ALVES LIMA LANDIM','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','PEDRO HENRIQUE ALVES DE SOUZA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','PEDRO HENRIQUE QUEIROZ MATIAS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','QUEILLA VICTORIA DO NASCIMENTO BRUGNARI','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','RAFAEL LEANDRO SOUSA LIMA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','RAQUEL DIOLINDA ALCANTARA DA SILVA','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','RICHARD SANTIAGO MIRANDA SANTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32','SOFIA VITAL DE ARAUJO SANTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33','SOPHIA CERQUEIRA SANTOS','4C Ezilda','19');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('34','SOPHIA EMILY DOS SANTOS SILVA','4C Ezilda','19');
