INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ALICIA PAOLA VASCONCELOS DE OLIVEIRA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANTONIO CARLOS DE JESUS BATISTA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','BERNARDO PEREIRA LOPES ROCHA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','DOUGLAS DA SILVA DUARTE COELHO','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','EMILLY MIRANDA DIAS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','EVERSON DA SILVA SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','GABRIEL DE OLIVEIRA VARJAO','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','GUILHERME AMORIM DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','HENRY GUSTAVO SANTOS DA SILVA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','*Transf* ISABELLE DA PAZ DE LIRA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','JEFERSON VASCONCELOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','JOAO PEDRO DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','JULIA DA SILVA SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','KETHLYN DOS SANTOS SILVA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','LARISSA DE SOUSA SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','MANOEL MESSIAS NETO DA SILVA GOMES','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','MARIA EDUARDA VARJAO DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','MARIA JULIA AGUIAR OLIVEIRA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','MARIANA SANTOS DA COSTA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','MAYANE DOMINIQUE DE OLIVEIRA SILVA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','MELYSSA DO CARMO AFFONSO','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','MIKAELLA DE FARIA OLIVEIRA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','MILTON LEAL DE LIMA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','PEDRO EDUARDO VESPERMANN DE SANTANA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','PEDRO HENRIQUE ALMEIDA DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','PEDRO HENRIQUE FERREIRA SOUZA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','RAYANNA SANTOS DA SILVA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','SAMUEL LOURENCO DE LIRA JUNIOR','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','SOPHIA BARBOSA RIBEIRO DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','SOPHYA DOS SANTOS DA SILVA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','TAYNNA VITORIA RAMOS DOS SANTOS','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32','WENDELL DA SILVA LIMA','5F Ezilda','22');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33','MARIA EDUARDA PORTO','5F Ezilda','22');
