INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','DANIEL BORGES SOARES','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','DAVI FERREIRA CONCEIÃ‡AO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','ELLOYSA DUARTE SANTOS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','ESTHER DE MELO ALVES','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','ESTHER VICTORIA DA SILVA SANTOS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','GABRIEL PEREIRA DE OLIVEIRA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','GUILHERME ARAUJO RODRIGUES','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','GUSTAVO TAVARES ROMERO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','HIGOR RYAN DA SILVA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','ISABELLA DA SILVA PEREIRA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','JULIA FERREIRA DA SILVA VENANCIO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','JULLYA VITORIA MATIAS SILVA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','KAUANNY SANTANA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','KAUANY DA SILVA SANTIAGO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','KAYLANE MIDORO HIGASHI DO REGO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','LETICIA GONCALVES MAIA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','LORENNA ARAUJO DOS SANTOS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','LUCAS FELIPE RODRIGUES CARDOSO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','MARCIO APARECIDO RODRIGUES DE SOUZA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','MARIA EDUARDA ALVES DA ROCHA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','MIGUEL BARBOSA CAZZARO','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','MONIQUE SOUSA DA SILVEIRA REIS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','RAFAEL IZIDORO ALVES','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','REBECA DE OLIVEIRA VIEIRA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','RUBEN DE SOUZA FERRAZ','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','SAMUEL DE SOUSA SANTOS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','THALITA SARA DA SILVA BARROS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','VICTOR HUGO SCHMDT GAMA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','VINICIUS OLIVEIRA SANTOS','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','WESLEY CAUA DE ANDRADE FERREIRA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','YASMIM CHAYLLA FEITOSA DA SILVA','4A Ezilda','17');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32','YASMIN VITORIA SOARES SILVA','4A Ezilda','17');
