INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ALANA MANUELLE DO NASCIMENTO ANDRADE','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANA JULIA FELINTO GOMES','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','ANA SOPHIA MARTINS BEZERRA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','DAVI FONTES DA SILVA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','EMANUELLY BRICKS LOPES','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','GUSTAVO DA SILVA TENQUINI EVANGELISTA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','GUSTAVO FELIPE DO NASCIMENTO','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','HENZO CUSTODIO DE ARAUJO','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','*Transf* ISADORA DE SOUZA SANTOS','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','JOAO PEDRO DA SILVA DOMINGOS','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','JULIANA STELUTTI RODRIGUES RAMOS','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','KAUA VALENTIM BERLATO ALMEIDA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','KAUAN PEDRO SOUZA BRUNHARA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','*Transf* LORENA VITORIA REIS SANTOS','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','MARCELA TIEMY HIGASHI DO REGO','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','MARIA EDUARDA DOS SANTOS BATISTA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','NYCOLLAS ARAUJO CASSIMIRO','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','PABLO NASCIMENTO FELIX CAVALCANTI','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','PAULO HENRYQUE CORDEIRO CANDIDO','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','PEDRO PAULO SILVA LIMA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','*Transf* SOFIA SILVA ROSA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','SOPHIA EMILIA COSTA DOS SANTOS','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','THAILA LETICIA BARBOSA AMORIM','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','THOMAS VICTOR ALVES GONZAGA','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','VICTOR GABRIEL MOTA ALVES','2E Ezilda','15');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','VICTOR RODRIGUES DOS SANTOS','2E Ezilda','15');
