INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ANA BEATRIZ DE OLIVEIRA GANCEDO','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANA JULIA BATISTA NASCIMENTO','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','ANA LUIZA RODRIGUES DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','BIANCA GUEDES DA ROCHA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','BIANCA RAYSSA DA SILVA MESSIAS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','BRAYAN SERRATE DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','BRYAN DO NASCIMENTO MOURA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','DANILO BRUNO MENDES LOPES','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','DAVI SOCRATES DE ASSIS BARROS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','ENZO MOURA MORENO','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','FELIPE FREIRE SOARES','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','GABRIELLY CRISTINA DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','GUILHERME ROCHA DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','GUSTAVO DA CONCEICAO VIDAL','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','HELOISA OLIVEIRA SANTIAGO','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','ISABELLA OLIVEIRA POZZATI DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','ISABELLY FERREIRA DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','JOAO VICTOR DE MIRANDA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','JOAO VICTOR NASCIMENTO DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','KIMBERLLY ALMEIDA DOS REIS SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','LINCOLN ANDRADE DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','LUCAS GABRIEL QUEIROZ DOS SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','LUCAS SILVA BRAZ','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','MATHEUS EMANUEL FERREIRA BARBOZA COSTA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','MATHEUS SERRA GOMES','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','MICHEL ADRIANO DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','RYAN LUCAS VIEIRA DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','SARA LUNA GOMES','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','SOPHIA LIMA DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','*Transf* THIERRY FRANCISCO DE FREITAS PRADO DA SILVA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','YAN DE ALCANTARA ROCHA SANTOS','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32','YASMIN LIMA OLIVEIRA','4B Ezilda','18');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('33','JONAS PAULINO BERNARDINO DA SILVA','4B Ezilda','18');
