
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','*Transf* ALESSANDRA CRISTINA LOPES PIRES','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANNA LIVIA TIMOTEO DO NASCIMENTO','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','CHRISTOPHER NATHAN SOLVELINO DE JESUS','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','*Transf* DÉBORA DANIELI CONCEIÇÃOO DE FREITAS','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','DEYLLON SHARLYSON DOS SANTOS SANTANA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','ESHILEY DA SILVA VESPERMANN','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','FELIPE MARTINS SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','GUSTAVO MUNHOZ DA SILVA VALENCA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','ISAQUE SANTIAGO STURCHI','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','*Transf* JULIA ELOA SOARES LOMBARDI','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','JULIA NUNES SOUSA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','KIMBERLYN LEMOS DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','LIVIA EVANGELISTA DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','*Transf* LUCAS BASSANI MIRANDA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','LUIS GUSTAVO RODRIGUES DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','MATHEUS FERREIRA DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','MELYSSA VITORIA DA SILVA SANTOS','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','MIGUEL LUCCA SILVA SANTOS','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','MIGUEL SILVA BATISTA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','NICOLLAS FERNANDO MACHADO DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','RYHANNA KAROLINE ARAUJO DE OLIVEIRA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','SAMUEL JUNIOR LUVIZOTTO DA SILVA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','SAMUEL PELEGRINO BARRETO DOS SANTOS','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','*Transf* SOFIA DA SILVA COSTA','2F Ezilda','16');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','THALIA LETICIA BARBOSA AMORIM','2F Ezilda','16');
