INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ANANDA VITORIA SANTOS DA SILVA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ANDREW GONCALVES FERREIRA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','BYANCA NUNES DE ARAUJO','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','ELOISA MODESTO GOMES','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','GABRIELA MARIA FREIRE DA SILVA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','GABRYEL SANTOS DE FREITAS','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','*Transf* GIULIA GOMES','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','GRAZIELLE DA SILVA COSTA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','GUSTAVO MENEZES SILVA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','ISADORA FERREIRA DE SOUZA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','*Transf* JOSUE SANTOS DE OLIVEIRA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','*Transf* KETHELLYN BEATRIZ BORGES SILVA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','LARISSA COLOMBO VARGAS ALVES','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','LETICYA DOMINGUES SANTANA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','LINIKER DE SOUZA ZANARDI','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','LUCAS BORGES DA SILVA PEREIRA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','MARCELO HENRIQUE GUIMARAES LIMA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','MARIA EDUARDA FELIPE DO NASCIMENTO','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','MONIQUE GABRIELLY DA SILVA SANTOS','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','MURILO ALMEIDA LINS','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','NICOLAS RODRIGUES COSTA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','PAULO HENRIQUE PINTO','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','PEDRO HENRIQUE XAVIER OLIVEIRA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','RAQUEL TAVORA SIMOES','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','REBEKA MONIKY MACH DORNELLAS','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','RYAN VITOR ANDRADE DO CARMO','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','THAUANY EMANUELLY LIMA SILVESTRE DA SILVA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','VICTOR HUGO DE JESUS COSTA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','VITOR DANIEL RODRIGUES SOUZA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','VITORIA SOARES MARTINS BORGES','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','YANI MAYANI SILVA PEREIRA','5D Ezilda','20');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('32','NYCOLLAS SOUZA OLIVEIRA','5D Ezilda','20');
