INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('1','ANA BEATRIZ DE SOUZA PEREIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('2','ARTHUR SILVA DOS SANTOS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('3','BENJAMIN EMANUEL ONOFRE','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('4','CAMILLE VITORIA DE SOUZA GOMES','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('5','CAROLINE CRISTINY SILVA DOS SANTOS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('6','DANIEL CHAVES SANTOS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('7','DANIEL SOUSA SINFAES','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('8','DANIELLY ARAUJO FERREIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('9','DAVI CARDOSO ALVES','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('10','DAVI MENDES DE OLIVEIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('11','ELIAS AMORIM PEREIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('12','ELOYSA VICTORIA MENDES DA SILVA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('13','EVELLYN DIAS SANTOS PEREIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('14','GIOVANNA OTAVIO SOUTO','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('15','GUILHERME CLAISON SOUZA DE CARVALHO DOS ANJOS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('16','*Transf* GUSTAVO MATEUS SOUZA DA SILVA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('17','JOYCE MARA CARDOSO ALVES MIRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('18','LORENA SANTOS NUNES ROSA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('19','LUCAS HENRIQUE SOARES DOS SANTOS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('20','LUCIANO ALVES DE AZEVEDO','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('21','LUIZ MARCELO XAVIER JORDAO','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('22','MARIA CLARA DA SILVA COSTA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('23','MARIA FERNANDA FERREIRA ALVES DE ALENCAR','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('24','NATHANAEL GUILHERME FREITAS DE MORGADO','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('25','*Transf* REBECA MARIA OLIVEIRA FERNANDES','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('26','RODRIGO DOS SANTOS MINEGRA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('27','RYAN MIKAEL LOPES MATIAS','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('28','*Transf* SOPHIA EMANUELLY SILVA BENJAMIM LIMA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('29','SUELLEN RODRIGUES SOARES','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('30','VITORIA VIEIRA DA SILVA','5E Ezilda','21');
INSERT INTO `escola04gin`.`alunos` (`numero`,`nome`,`turma`,`idTurma`) VALUES ('31','YASMIN FERREIRA DA SILVA','5E Ezilda','21');
